services:
  - type: web
    name: car-blur-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "TRUE"
